image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 16 x64
  - yarn
  - yarn install

build_script:
  - yarn dist --publish always

test: off
